### ISSUE TITLE
La clase OrderCES.Builder no permite hacer pagos con decimales.

### ISSUE THREAD

**Issue by smarcilla** [majulvez/easyredsys#2]
Hola,

Estoy utilizando el pago seguro y me acabo de dar cuenta que la cantidad (campo amount) es de tipo long. Entonces, ¿no es posible enviar un pago de 9,99?

`    public static class Builder {

        private long merchantCode;
        private long terminal;
        private String transactionType;
        private long currency;
        private int consumerLanguage;
        private String order;
        private long amount;
        private String urlOk;
        private String urlKo;
        private String urlNotification;
        private String productDescription;
        private String payMethods;`

Un saludo.

**Comment by majulvez** [comment]
Sí. Para un pago de 9.99 hay que enviar un valor 999. Los últimos 2 dígitos son siempre decimales. Esto lo puedes encontrar reflejado en la documentación oficial de redsys

Por ejemplo, para hacer un pago de 10 hay que enviar 1000 en el campo amount.

Un saludo

**Comment by smarcilla** [comment]
Gracias,

Lo probé y ya funciona perfectamente.

Un saludo.
