### ISSUE TITLE
Consulta SOAP codebase proposal

### ISSUE THREAD

**Issue by laurentperez** [majulvez/easyredsys#22]
Hi

Not a bug.
I've got a working implementation of Consulta SOAP (see https://soportetpv.com/wp-content/uploads/2018/09/Santander-TPV-consulta-SOAP.pdf)
This is used to see Ds_Orders statuses, this is a read-only WS for status and monitoring purposes

But I wrote it in PHP ;) 
Would you be interested in my code for a Java port ?

Regards

**Comment by majulvez** [comment]
Hi @laurentperez 

I'm sorry but I don't have time to do it but you're more than welcome to contribute to this project

Thanks
