### ISSUE TITLE
Error en códigos de error

### ISSUE THREAD

**Issue by Canos** [majulvez/easyredsys#8]
En la siguiente línea se introduce como código de error un número de clave diferente al del valor. Creo que se trata de un error

https://github.com/majulvez/easyredsys/blob/eac923e8df819275e5df8edae9621d5ff84c873a/easyredsys-client/src/main/java/com/miguelangeljulvez/easyredsys/client/util/ResponseCodes.java#L26

Además, según Alvaro Lara, se han añadido algunos códigos:  
https://www.alvarolara.com/2015/05/09/codigos-de-respuesta-en-los-tpv-de-redsys/ 
¿Ves conveniente añadirlos? Podría hacer un PR si consiguiera sacar algo de tiempo.

Gracias por tu esfuerzo en el proyecto

**Comment by majulvez** [comment]
Hola @Canos ,

sí, crees muy bien. Es un error. Tendrían que ser dos líneas 

errorResponseCodes.put("102", "102");
errorResponseCodes.put("106", "106");

Sería fantástico si pudieras colaborar en el proyecto. Cualquier ayuda siempre es bienvenida :)

Para añadir los códigos de error que faltan sería añadir las líneas correspondientes en ResponsesCodes.java y luego añadir su traducción a https://github.com/majulvez/easyredsys/blob/eac923e8df819275e5df8edae9621d5ff84c873a/easyredsys-client/src/main/resources/Language.properties

Inicialmente hice un hashmap<string,strin> para esto porque la idea era poner el código de error y luego una property en Language.properties con una key un poco mas explicativa (tipo "card-expired" en lugar de 101) para que fuera mas fácil identificar el código de error con lo que significa sin tener que ir a ver su traducción en el Language.properties, pero al final se quedó así.

Muchas gracias por tu ayuda
